return {
    name = "Hakurei Reimu",
    subname = "Paradise Miko",
    Talent1name = "Minute Precision",
    Talent1des = [[Restore §g0.4§d life/s]],
    Talent2name = "Poem in Five Steps",
    Talent2des = [[When play level is a §bmultiple of 5§d,
the EXP for Upgrading is fixed at §g25§d.]],
    Talent3name = "Things yet not Things",
    Talent3des = [[When obtaining §gBenefit§d,
gain an identical §gBenefit§d.]],
    spelldes = [[Shoot §g%d§d super large tracking LIGHT BALLs to subdue enemies,
each LIGHT BALLS causes an expected damage of §g%d%%§d of ATK,
and grants §g%0.2f§d seconds of Invincibility.]],
}