return {
    Chiruno = "琪露诺",
    Daiyousei = "大妖精",
    Rumia = "露米娅",
    Wakasagihime = "若鹭姬",
    Medicine = "梅蒂欣·梅兰可莉",
    Kogasa = "多多良小伞",
    Yukari = "八云紫",
    LunaChild = "露娜切露德",
    StarSapphire = "斯塔萨菲雅",
    SunnyMilk = "桑尼米尔克",
    Neet = "蓬莱山辉夜",
    Yagokoro = "八意永琳",
    Clownpiece = "克劳恩皮丝",
    Seiran = "清兰",
    Junko = "纯狐",
    Ringo = "铃瑚",
    Whitelily = "莉莉白",
    Yamame = "黑谷山女",
    Murasa = "村纱水蜜",
}