return {
    Chiruno = "Chiruno",
    Daiyousei = "Daiyousei",
    Rumia = "Rumia",
    Wakasagihime = "Wakasagihime",
    Medicine = "Medicine Melancholy",
    Kogasa = "Tatara Kogasa",
    Yukari = "Yakumo Yukari",
    LunaChild = "Luna Child",
    StarSapphire = "Star Sapphire",
    SunnyMilk = "Sunny Milk",
    Neet = "Houraisan Kaguya",
    Yagokoro = "Yagokoro Eirin",
    Clownpiece = "Clownpiece",
    Seiran = "Seiran",
    Junko = "Junko",
    Ringo = "Ringo",
    Whitelily = "Whitelily",
    Murasa = "Murasa",
}