local module = "achievement"
loadLanguageModule(module, "mod\\achievement_des")
local function t(str)
    return Trans(module, str) or { "", "" }
end

local function AfterWeather()
    return scoredata.FirstWeather
end--知道有天气后
local function After5season()
    return scoredata.First5Season
end--知道有里季节后
local _DefineAchievement = function(id, rank, noget_insp, hide, showcond)
    DefineAchievement(id, rank, t(id)[1], t(id)[2], noget_insp, hide, showcond)
end

_DefineAchievement(1, 1)
_DefineAchievement(11, 1, true)
_DefineAchievement(17, 1, true)
_DefineAchievement(18, 1, true)
_DefineAchievement(19, 1, true)
_DefineAchievement(20, 1)
_DefineAchievement(21, 1)
_DefineAchievement(22, 1)
_DefineAchievement(23, 1)
_DefineAchievement(24, 1)
_DefineAchievement(25, 1, false, true)
_DefineAchievement(26, 1, false, true)
_DefineAchievement(27, 1)
_DefineAchievement(28, 1)
_DefineAchievement(29, 1)
_DefineAchievement(30, 1)
_DefineAchievement(31, 1)
_DefineAchievement(32, 1)
_DefineAchievement(33, 1)
_DefineAchievement(124, 1)
_DefineAchievement(125, 1)
_DefineAchievement(132, 1)
_DefineAchievement(133, 1)

_DefineAchievement(2, 2, true)
_DefineAchievement(3, 2)
_DefineAchievement(7, 2)
_DefineAchievement(12, 2, true, true)
_DefineAchievement(13, 2, true)
_DefineAchievement(14, 2, true)
_DefineAchievement(34, 2, true, true)
_DefineAchievement(35, 2)
_DefineAchievement(36, 2)
_DefineAchievement(37, 2)
_DefineAchievement(38, 2)
_DefineAchievement(39, 2)
_DefineAchievement(40, 2, true, true)
_DefineAchievement(41, 2)
_DefineAchievement(42, 2, true, true)
_DefineAchievement(43, 2, true)
_DefineAchievement(44, 2, true)
_DefineAchievement(45, 2, true)
_DefineAchievement(46, 2, true)
_DefineAchievement(47, 2)
_DefineAchievement(48, 2)
_DefineAchievement(49, 2, true)
_DefineAchievement(50, 2, true, true)
_DefineAchievement(51, 2, true, true)
_DefineAchievement(52, 2)
_DefineAchievement(126, 2)
_DefineAchievement(127, 2)
_DefineAchievement(134, 2)
_DefineAchievement(135, 2)

_DefineAchievement(4, 3)
_DefineAchievement(53, 3, true, true)
_DefineAchievement(54, 3, false, true)
_DefineAchievement(55, 3)
_DefineAchievement(56, 3)
_DefineAchievement(57, 3)
_DefineAchievement(58, 3)
_DefineAchievement(59, 3)
_DefineAchievement(60, 3)
_DefineAchievement(61, 3, true)
_DefineAchievement(62, 3, true, true)
_DefineAchievement(63, 3, true, true)
_DefineAchievement(64, 3, true, true)
_DefineAchievement(65, 3)
_DefineAchievement(66, 3, true, true)
_DefineAchievement(67, 3)
_DefineAchievement(68, 3)
_DefineAchievement(69, 3, true)
_DefineAchievement(70, 3, true)
_DefineAchievement(71, 3, true, true)
_DefineAchievement(72, 3, true)
_DefineAchievement(73, 3, true, true)
_DefineAchievement(74, 3, true)
_DefineAchievement(75, 3, true)
_DefineAchievement(76, 3, true)
_DefineAchievement(77, 3, true, true)
_DefineAchievement(78, 3, true, true)
_DefineAchievement(79, 3)
_DefineAchievement(80, 3, true, true)
_DefineAchievement(81, 3, true, true)
_DefineAchievement(82, 3, true, true)
_DefineAchievement(120, 3, true, true)
_DefineAchievement(128, 3)
_DefineAchievement(129, 3)
_DefineAchievement(136, 3)
_DefineAchievement(137, 3)
_DefineAchievement(140, 3)

_DefineAchievement(5, 4)
_DefineAchievement(8, 4)
_DefineAchievement(15, 4, true, true)
_DefineAchievement(16, 4)
_DefineAchievement(83, 4, true, true)
_DefineAchievement(84, 4, true, true)
_DefineAchievement(85, 4, true, true)
_DefineAchievement(86, 4, true, true)
_DefineAchievement(87, 4)
_DefineAchievement(88, 4)
_DefineAchievement(89, 4)
_DefineAchievement(90, 4, true, true)
_DefineAchievement(91, 4)
_DefineAchievement(92, 4, true, true)
_DefineAchievement(93, 4)
_DefineAchievement(94, 4)
_DefineAchievement(95, 4)
_DefineAchievement(96, 4)
_DefineAchievement(97, 4)
_DefineAchievement(98, 4, true, true)
_DefineAchievement(99, 4, true, true)
_DefineAchievement(100, 4, true, true)
_DefineAchievement(101, 4, true, true)
_DefineAchievement(102, 4, true)
_DefineAchievement(103, 4, true, true)
_DefineAchievement(104, 4, true, true)
_DefineAchievement(105, 4, true, true)
_DefineAchievement(106, 4, true, true)
_DefineAchievement(107, 4, true, true)
_DefineAchievement(108, 4, true, true)
_DefineAchievement(121, 4, true, true)
_DefineAchievement(122, 4)
_DefineAchievement(123, 4)
_DefineAchievement(130, 4)
_DefineAchievement(131, 4)
_DefineAchievement(139, 4)
_DefineAchievement(141, 4)
_DefineAchievement(142, 4)
_DefineAchievement(143, 4)
_DefineAchievement(147, 4, true, true)
_DefineAchievement(148, 4, true, true)
_DefineAchievement(149, 4, true, true)
_DefineAchievement(150, 4, true, true)
_DefineAchievement(151, 4, true, true)

_DefineAchievement(6, 5)
_DefineAchievement(9, 5)
_DefineAchievement(109, 5, true)
_DefineAchievement(110, 5, true)
_DefineAchievement(111, 5, true)
_DefineAchievement(112, 5)
_DefineAchievement(113, 5, true)
_DefineAchievement(114, 5, true)
_DefineAchievement(115, 5, true)
_DefineAchievement(138, 5)
_DefineAchievement(144, 5)
_DefineAchievement(146, 5, true)

_DefineAchievement(10, 6, false, true)
_DefineAchievement(116, 6, false, true)
_DefineAchievement(117, 6)
_DefineAchievement(118, 6, true)
_DefineAchievement(119, 6, true)
_DefineAchievement(145, 6)
